services:
  quodb:
    build:
      context: .
      args:
        GIT_COMMIT: ${GIT_COMMIT:-unknown}
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/app/config.json
      - quodb_data:/app/data
    restart: unless-stopped

volumes:
  quodb_data:
    name: quodb_data
    external: true
